# Generated by Django 2.2 on 2019-04-08 09:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('M_USER', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=11)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TopUP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('transection_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('topup_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TopUP_Account', to='M_USER.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('transection_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_Account', to='M_USER.Account')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('transection_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('card_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Credit_card_Account', to='M_USER.Account')),
            ],
        ),
    ]
