# Generated by Django 2.2 on 2019-04-08 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('M_USER', '0002_account_creditcard_payments_topup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
